services:
  nordvpn-container:
    build: .
    image: nordvpn-yt-dlp:latest
    container_name: nordvpn_app
    cap_add:
      - NET_ADMIN               # needed for network management
      - SYS_MODULE              # needed for kernel modules
    devices:
      - /dev/net/tun            # needed for VPN tunel
    environment:
      - NORDVPN_TOKEN=${NORDVPN_TOKEN}              # ref .env
      - NORDVPN_COUNTRY=${NORDVPN_COUNTRY:-France}  # ref .env
    stdin_open: true
    tty: true
    volumes:
      - ./downloads:/app/downloads
      - nordvpn-data:/var/lib/nordvpn
    restart: unless-stopped

volumes:
  nordvpn-data: